### ISSUE TITLE
Collaboration with littlesis?

### ISSUE THREAD

**Issue by aspiers** [sophieehill/my-little-crony#2]
Hi Sophie!

I just [tweeted you](https://twitter.com/adamspiers/status/1326481174093500417) but then thought this might be a better place to share my thoughts.

Firstly, congrats - this is really great work!  I think visualisations can be extremely potent in exposing cronyism and other corruption.

I was wondering if you were aware of https://littlesis.org/ ? It's an awesome project for crowd-sourcing data on and connections between powerful people and organizations in order to bring transparency and shine a light on murky areas.  As you can see from [their data summary](https://littlesis.org/about), they have an enormous database already.

They also have an [Oligrapher](https://littlesis.org/oligrapher) graphing tool which has some similarities with yours, although of course some differences too, e.g. it is designed to enable non-technical folk such as journalists curate and collaborate on their own visualisations (which are obviously small subsets of the huge littlesis database).  I think Oligrapher also has some low-hanging fruit in terms of simple UI tweaks which could be made to vastly improve the usability, for example [zooming with the mouse wheel](https://github.com/public-accountability/oligrapher/issues/59) just like My Little Crony already allows.

I have no affiliation with LittleSis, but I've been very impressed by all their technical and organisational achievements so far, and I think the more that people working in this area can combine efforts, the more powerful the whole movement can become. 

By the way, very cool to come across another ex-Oxford maths graduate in this space ;-)  Sadly I left academia a lot earlier than you, but I've been working with Free / Open Source software since I discovered it as an undergrad, and in the last few years have become quite involved in the UK political "hacktivism" scene (legal activities only!)

**Comment by sophieehill** [comment]
Hi Adam,

That's awesome, I hadn't seen LittleSis before but it looks like a great
organization. I'll reach out to them and see if I can help out at all once
things calm down a bit with my app (currently just trying to make sure the
server doesn't go down again!).

Cheers,
Sophie
